### PR TITLE
[feat]: add multiple classes

### PR DESCRIPTION
**Pull request by Scrum**

### CODE REVIEW

**Comment by Scrum** [comment]
@voischev @maltsev ping.

**Comment by maltsev** [comment]
I guess we still should support node 0.12 because [posthtml does support it](https://github.com/posthtml/posthtml/blob/master/package.json#L18). And It seems that new versions of the dependencies aren't supported by that old node version. Should we downgrade them then (i.e. revert 0023145)?

@GitScrum could you please also merge 373de7b and 375769d into one commit?

**Comment by Scrum** [comment]
@maltsev Support 0.12 is no longer relevant, but I'm downgrade

**Comment by maltsev** [comment]
Thanks! Can you also rebase your commits? It'd be nice to have a clean commit history :-)

**Pull request closed without merging**
